### ISSUE TITLE
Possibility to open in vertical / horizontal split

### ISSUE THREAD

**Issue by huijunchen9260** [VebbNix/dmenufm.vim#3]
Is it possible to have either a different command in vim, or a dmenu prompt to open the chosen file in vertical / horizontal split?

Today I suddenly want to do it but I just realize that I cannot LOL

**Comment by VebbNix** [comment]
New variable in latest commit dictates what command is used to open the file, read the new README Configuration section for more info.

Thanks for suggesting this!
