### ISSUE TITLE
No Choice behavior

### ISSUE THREAD

**Issue by huijunchen9260** [VebbNix/dmenufm.vim#4]
Today I realize that if I choose nothing (i.e., press escape) in dmenufm.vim, it will have two possible situations:

1. If the file is saved, then it will do nothing.
2. If the file is just created in the buffer (i.e., the situation when you just press `vim` in terminal), it will have the following error:

![image](https://user-images.githubusercontent.com/54217138/77253373-0ff27780-6c30-11ea-9210-c497b9dc3c97.png)

Does it possible to eliminate or suppress this error?

**Comment by VebbNix** [comment]
Fixed with newest commit. Now it will simply echo "No file selected!" instead of throwing an error like this.
